In [25]:
import torch
device = 'mps' if torch.mps.is_available() else 'cpu'
torch.set_default_device('mps')
print(device)

mps


In [26]:
randint = torch.randint(-100,100,(6,))
randint

tensor([-80,  51, -28,  14, -91,  -7], device='mps:0')

In [27]:
zeros = torch.zeros(5)
zeros

tensor([0., 0., 0., 0., 0.], device='mps:0')

In [28]:
ones = torch.ones(5,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], device='mps:0')

In [29]:
empty = torch.empty(3,2)
empty

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], device='mps:0')

In [30]:
linspace = torch.linspace(10, 50, steps=5)
linspace

tensor([10., 20., 30., 40., 50.], device='mps:0')

In [31]:
logspace = torch.logspace(-5, 10, steps=7)
logspace

NotImplementedError: The operator 'aten::logspace.out' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

In [33]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], device='mps:0')

In [34]:
a = torch.empty(size=(2,5), dtype=torch.int64)
print(a)
empty_like = torch.empty_like(a)
empty_like

tensor([[4575657222473777152, 4575657222473777152,          1065353216,
                          18,                  24],
        [                  0,                   0,                   0,
                           0,                   0]], device='mps:0')


tensor([[4575657222473777152, 4575657222473777152,   72340173886586880,
                           1,                   0],
        [                  0,                   0,                   0,
                           0,                   0]], device='mps:0')

In [35]:
tensor1 = torch.randn(6)
tensor2 = torch.randn(6)
tensor3 = torch.randn(6)

# Stack them into a single 3D tensor
stack = torch.stack((tensor1, tensor2, tensor3))
stack


tensor([[-1.0188,  0.6126, -1.0892, -1.8316, -1.6611,  0.6993],
        [-1.4660, -0.6745,  0.2123,  0.6066,  0.8010, -0.5768],
        [-0.7665, -0.0062, -0.2945,  0.1212, -1.0758,  1.6891]],
       device='mps:0')

In [36]:
tensor = torch.tensor([[0,1],[1,0],[0,0],[1,1]])
print(tensor)
print(tensor.device)

mps:0
