In [2]:
import torch
import time
import numpy as np
device = 'mps' if torch.mps.is_available() else 'cpu'
print(device)
print(torch.get_default_device())

mps
cpu


In [6]:
%%time
start_time = time.time()

# Matrix ops
zeros = torch.zeros(1,1)
end_time = time.time() - start_time

print(f'Elapsed Time: {end_time:.8f}')
print(zeros.device)

Elapsed Time: 0.00028300
cpu
CPU times: user 478 µs, sys: 99 µs, total: 577 µs
Wall time: 427 µs


In [5]:
torch_rand1 = torch.rand(100,100,100,100).to(device)
# print(torch_rand1)
torch_rand2 = torch.rand(100,100,100,100).to(device)
# print(torch_rand2)

np_rand1 = torch.rand(100,100,100,100)
# print(np_rand1)
np_rand2 = torch.rand(100,100,100,100)
# print(np_rand2)

# GPU Matrix Ops
start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time() - start_time
print(f'Elapsed GPU Time: {end_time:.8f}')

# CPU Matrix Ops
start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)

end_time = time.time() - start_time
print(f'Elapsed CPU Time: {end_time:.8f}')

Elapsed GPU Time: 0.00519109
Elapsed CPU Time: 0.05970716


In [21]:
# Probabilities tensor
# First parameter is % => 0, Second is % => 1
probabilities = torch.tensor([0.5,0.01])

# Draw number of samples using probabilty distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
samples


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
tensor = torch.tensor([1,2,3,4])
cat = torch.cat((tensor, torch.tensor([5])))
cat

tensor([1, 2, 3, 4, 5])

In [27]:
triange_lower = torch.tril(torch.ones(5,5))
triange_lower

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [28]:
triangle_upper = torch.triu(torch.ones(5,5))
triangle_upper

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [33]:
masked_fill = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
masked_fill

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [34]:
torch.exp(masked_fill)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [37]:
input = torch.rand(2,3,4)
print(input)
transpose = input.transpose(0,2)
print(transpose)

tensor([[[0.0840, 0.8864, 0.1589, 0.1865],
         [0.4075, 0.5182, 0.6523, 0.6982],
         [0.9059, 0.9534, 0.3744, 0.2140]],

        [[0.1506, 0.7639, 0.4985, 0.0129],
         [0.2929, 0.1405, 0.7912, 0.6455],
         [0.8052, 0.7514, 0.1511, 0.1589]]])
tensor([[[0.0840, 0.1506],
         [0.4075, 0.2929],
         [0.9059, 0.8052]],

        [[0.8864, 0.7639],
         [0.5182, 0.1405],
         [0.9534, 0.7514]],

        [[0.1589, 0.4985],
         [0.6523, 0.7912],
         [0.3744, 0.1511]],

        [[0.1865, 0.0129],
         [0.6982, 0.6455],
         [0.2140, 0.1589]]])


In [40]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3, bias=False)
print(linear(sample))


tensor([ 4.0156, -9.0152, -8.8550], grad_fn=<SqueezeBackward4>)


In [43]:
import torch.nn.functional as F

tensor = torch.tensor([1.0,2.0,3.0])

softmax_output = F.softmax(tensor, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [ ]:
embedding_dim = 5 
vocab_size = 81

embedding_vector = nn.Embedding(vocab_size, embedding_dim)

example_tensor = torch.randint(0, 5,(vocab_size,))
embedding_output = embedding_vector(example_tensor)

print(embedding_output.shape)
print(embedding_output)
